name: Adjust App environment
description: make adjustment specific for selected App

inputs:
  name:
    description: application name
    required: true

runs:
  using: "composite"
  steps:
    - name: adjust env -> Flashy
      if: inputs.name == 'flashy'
      working-directory: tests/_flagship-app
      run: |
        ls -l .
        pip install -r requirements-dev.txt -f $TORCH_URL
        pip install -e . -f $TORCH_URL
      shell: bash

    - name: adjust env -> Muse
      if: inputs.name == 'muse'
      working-directory: tests/
      run: |
        pip install -e _flagship-app -f $TORCH_URL
        cp _flagship-app/tests/test_app.py \
          integrations_app/flagship/test_${{ inputs.name }}.py
      shell: bash

    - name: adjust env -> Jupyter
      if: inputs.name == 'jupyter'
      working-directory: tests/
      run: |
        pip install -e _flagship-app -f $TORCH_URL
        # pip install -r _flagship-app/tests/requirements-dev.txt
        cp _flagship-app/tests/test_jupyter_app.py \
          integrations_app/flagship/test_${{ inputs.name }}.py
      shell: bash
